# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

concurrency: production

on:
  workflow_dispatch:
    inputs:
      RESTART_TIME:
        description: 'Restarts server in given seconds'
  push:
    branches: [ main ]

jobs:
  build:
    name: Ant Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -Dbuild=${{ github.workspace }}/build -f build.xml
    - name: Upload Build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/*.zip
        retention-days: 7
        if-no-files-found: error
        
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs: build
  #   steps:
  #     - name: Download Build artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #     - name: Renaming bundle to commit SHA
  #       run: mv *.zip ${{ github.sha }}.zip
  #     - name: Deploy to Server
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         ARGS: "-rlgoDzvc -i"
  #         REMOTE_HOST: ${{ secrets.HOST }}
  #         REMOTE_USER: ${{ secrets.USER }}
  #         TARGET: ${{ secrets.TARGET }}
  #         SCRIPT_AFTER: |
  #           echo $RSYNC_STDOUT
